### ISSUE TITLE
create_block_blob function doesn't support IO stream

### ISSUE THREAD

**Issue by pratt06** [Azure/azure-storage-ruby#100]
I tried using the ruby SDK and redirected the Linux IO stream to the ruby SDK API. 
 
Example of what I are trying :
cat file | azure_blob_service.create_block_blob("firstcontainer","image-blob", $stdin)
 
 
I am getting below exception
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/stuartpreston-azure-sdk-for-ruby-0.7.2/lib/azure/core/service.rb:34:in `call': undefined method `encoding' for #<IO:<STDIN>> (NoMethodError)
Did you mean?  set_encoding
from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/stuartpreston-azure-sdk-for-ruby-0.7.2/lib/azure/core/filtered_service.rb:33:in `call'
from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/stuartpreston-azure-sdk-for-ruby-0.7.2/lib/azure/core/signed_service.rb:39:in `call'
from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/stuartpreston-azure-sdk-for-ruby-0.7.2/lib/azure/blob/blob_service.rb:608:in `create_block_blob'
from /Users/prateegu/Desktop/script.rb:10:in `<main>'

I checked the /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/stuartpreston-azure-sdk-for-ruby-0.7.2/lib/azure/core/service.rb file's 34 line and looks like there is not distinction between String and IO class stream object. Can you please get it checked and fixed?

**Comment by katmsft** [comment]
After some investigation, I found that in [azure-ruby-asm-core](https://github.com/Azure/azure-ruby-asm-core/blob/master/lib/azure/core/http/http_request.rb#L156), the `Content-Length` header is get from `size()` function no matter the IO has this function implemented or not. There could be further problems because your log actually reports a similar issue of getting `Content-Encoding`. it needs to release new version and this repo should adjust accordingly to fully solve the issue.

For now, instead of running `cat file | azure_blob_service.create_block_blob("firstcontainer","image-blob", $stdin)`, is there any chance that you could run `azure_blob_service.create_block_blob("firstcontainer","image-blob", File.open(file))` instead? It should do the same thing.

**Comment by pratt06** [comment]
That was just an example, in my exact use case I am using a db backup command to write to a  stream at runtime and passing that to azure Ruby SDK. It's in such way because the file size after creation would be ~3-4 TB. So, we don't want to save it on disc first and then stream it.

**Comment by katmsft** [comment]
In that way I'm afraid that we do not currently support making blobs larger than 256MB in a single API call. The convenience API is in our backlog and to be implemented in the future.
Currently you can all these three APIs to do the job:
```
create_block_blob #with empty content
put_blob_block #each of the block can be as large as 100MB. The content can be read from stream.
commit_blob_blocks # with the list of blocks you just put with put_blob_block
```
Sorry for the inconvenience.

**Comment by pratt06** [comment]
Is there any plan to support streaming through az CLI command as well for creating large [~TB's] blobs?

**Comment by katmsft** [comment]
Sorry for the late response.
First, please clarify what you mean by 'streaming through az CLI command'. Now it is using Python library so Ruby is not involved.
Second, our original plan is to push Ruby to GA. This includes feature parity to service version 2016-05-31 and stress test and other non-convenience features. We are currently discussing internally if we should adjust our plan due to user request of parallel upload and streaming. Please stay tuned. I will update this issue whenever a conclusion has been drawn.

**Comment by seguler** [comment]
Hi @pratt06 

We are expecting to support piping from stdin in AzCopy release in the next few months. Alternatively, another open source solution is blobxfer: https://github.com/Azure/blobxfer/tree/develop 

Bloxfer beta release now supports the streaming. Here is an example:
cat myfile | blobxfer upload --storage-account sdksampleperftest --remote-path path/to/blob --storage-account-key ....== --local-path - --rename

Here are the documents on how to use blobxfer beta: https://github.com/Azure/blobxfer/tree/develop/docs

Let me know if this helps

**Comment by pratt06** [comment]
Hi @seguler 
Thanks for pointing out blobxfer, I will try using it. 
Regarding the plan to support stdin piping in azcopy, could you please provide the exact timelines? If your timelines falls under our stage/prod release we can actually wait for this feature to be available in azcopy rather than using any 3rd party library.

**Comment by seguler** [comment]
I'll check with my team and let you know regarding the timelines.

**Comment by pratt06** [comment]
@seguler 
I was able to use blobxfer for piping based streaming for stdin.

Any update on the timeline front for supporting stdin based piping in azcopy?

**Comment by yaxia** [comment]
@pratt06  The AzCopy has been released. Please follow the instruction here: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-linux 

So closing this issue.

**Comment by pratt06** [comment]
@yaxia I read the document page, but nowhere in mentions how to upload a blob which is getting generated through stdin piping operator.

@seguler  above has pointed to use blobxfer, @yaxia can you please check it and point me to the right example?

**Comment by seguler** [comment]
Sorry about the confusion. I haven't updated the documentation yet as there is a bug we are going to fix before we advertise this feature. It works, but the cursor automatically sets to left/top as soon as the transfer finishes, bringing the command ran after the result of the command on a Putty window.

If you would like to try out, download the latest azcopy; here is a sample:
`tar -czf - mydirectorye | azcopy --destination "https://myaccount.blob.core.windows.net/data/test.tar.gz?st=2018-01-05T13%3A35%3A00Z&se=2018-01-08T13%3A35%3A00Z&sp=rwdl&sv=2017-04-17&sr=c&sig=...."`

**Comment by Nidhi10** [comment]
Hi @seguler ,
I tried the above example on a ubuntu machine-
```tar -Oczf  my mydirectorye | azcopy --destination https://devopseastus2nm1.blob.core.windows.net/es-devops-nm1-panmishr-na1dc1-fs-image-azure-eastus/?st=2018-01-24T09%3A46%3A00Z&se=2018-01-27T09%3A46%3A00Z&sp=rwl&sv=2015-12-11&sr=c&sig=***```

also, with quotes - 

```tar -Oczf  my mydirectorye | azcopy --destination "https://devopseastus2nm1.blob.core.windows.net/es-devops-nm1-panmishr-na1dc1-fs-image-azure-eastus/?st=2018-01-24T09%3A46%3A00Z&se=2018-01-27T09%3A46%3A00Z&sp=rwl&sv=2015-12-11&sr=c&sig=***"```

I get this error everytime  -

```The syntax of the command is incorrect. Unrecognized command or argument '--destination https://devopseastus2nm1.blob.core.windows.net/es-devops-nm1-panmishr-na1dc1-fs-image-azure-eastus/?st=2018-01-24T09%3A46%3A00Z'11&sr=c&sig=***```

Is is expecting a --source option too? Could you please help me here?
I am on version ```azcopy 7.1.0-netcorepreview```

**Comment by seguler** [comment]
@EmmaZhu any ideas ?

**Comment by EmmaZhu** [comment]
@Nidhi10 
I've also tried with the same command line, it doesn't report the error you met. Could you share the version of Ubuntu you were trying?

BTW, uploading from piping can only upload to a blob with exactly name indicated. You'd need to specify the exactly name instead of a folder. AzCopy recognizes `https://devopseastus2nm1.blob.core.windows.net/es-devops-nm1-panmishr-na1dc1-fs-image-azure-eastus/?st=2018-01-24T09%3A46%3A00Z'11&sr=c&sig=*** ` as a folder, for its name ends with the directory separator `'/'`.

**Comment by Nidhi10** [comment]
@EmmaZhu  I installed azcopy by following 'installation on Linux' steps mentioned  [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-linux).
I am on Ubuntu version ```16.04.3 LTS (Xenial Xerus)```

I tried the same command by adding a `=`, as below, which worked for me. It still did not work with spaces.
```tar -czf  test mydirectorye | azcopy --destination="https://azcopystoragee.blob.core.windows.net/test/test.tar.gz?st=2018-01-29T07%3A34%3A00Z&se=2018-03-30T07%3A34%3A00Z&sp=rwl&sv=2015-12-11&sr=c&sig=***"```

@seguler @EmmaZhu  Also, Is azcopy supported on centos 6?  I tried installing it on centos 6.8 and faced issues with .Net core installation, which landed me [here](https://github.com/PowerShell/PowerShell/issues/3563)
Could you please confirm?

**Comment by EmmaZhu** [comment]
@Nidhi10  

Technically, AzCopy should work on all platforms with .Net Core runtime installed, although we trust .Net Core's implementation so we didn't test AzCopy on all platforms.
What error did you meet with .Net Core installation? Could you send detailed installation failures to corefxdev@microsoft.com ? I think they would be happy to resolve the issue you found.

**Comment by vinjiang** [comment]
Please let us know if you need further assistance.

**Comment by tusharsappal** [comment]
HI ,
Lets not close this issue .

We are trying to use the azcopy in our centos 6.9 VM .

We are getting the following exception 

```root@chef:/tmp/prateek # tar -czvf test.tar.gz file.txt | azcopy --destination="https://devopseastus2an.blob.core.windows.net/es-devops-east-us-2/test.tar.gz" --dest-key=$AZURE_STORAGE_KEY --verbose
 
[2018/04/12 06:23:17.656-07:00] >>>>>>>>>>>>>>>>
[2018/04/12 06:23:17.726-07:00][VERBOSE] Finished: 0 file(s), 0 B; Average Speed:0 B/s.
[2018/04/12 06:23:17.736-07:00][VERBOSE] 7.1.0 : azcopy --destination=https://devopseastus2an.blob.core.windows.net/es-devops-east-us-2/test.tar.gz --dest-key=xxx --verbose
[2018/04/12 06:23:17.870-07:00][VERBOSE] Attempt to parse address '' to a directory as a candidate location succeeded.
[2018/04/12 06:23:17.876-07:00][VERBOSE] Attempt to parse address '' to a single file as a candidate location succeeded.
[2018/04/12 06:23:18.727-07:00][VERBOSE] Source is interpreted as a StandardInput.
[2018/04/12 06:23:18.851-07:00][VERBOSE] Attempt to parse address 'https://devopseastus2an.blob.core.windows.net/es-devops-east-us-2/test.tar.gz' to a directory as a candidate location succeeded.
[2018/04/12 06:23:18.892-07:00][VERBOSE] Attempt to parse address 'https://devopseastus2an.blob.core.windows.net/es-devops-east-us-2/test.tar.gz' to a single file as a candidate location succeeded.
[2018/04/12 06:23:18.901-07:00][VERBOSE] Interpreting destination as a single file as the provided source is a single file.
[2018/04/12 06:23:18.906-07:00][VERBOSE] Destination is interpreted as a Cloud blob: https://devopseastus2an.blob.core.windows.net/es-devops-east-us-2/test.tar.gz.
[2018/04/12 06:23:19][ERROR] Error parsing destination location "https://devopseastus2an.blob.core.windows.net/es-devops-east-us-2/test.tar.gz": The type initializer for 'System.Net.Http.CurlHandler' threThe type initializer for 'Http' threw an exception.py --help destination" or use verbose option --verbose.```

**Comment by EmmaZhu** [comment]
@tusharsappal 
Are you using AzCopy with version of 7.1.0-netcorepreview? AzCopy would require .Net Core runtime to be installed, .Net Core has dependency on libcurl.  Do you have  libcurl installed on the VM?

We are working on a release of AzCopy which opted out dependency on libcurl, this should be released in several days. Hope you can have a try with it after it's released.

Thanks
Emma
