### ISSUE TITLE
Could not retry when TCP connection timeouted

### ISSUE THREAD

**Issue by devchick** [Azure/azure-storage-ruby#108]
I got a timeout error for TCP connection, but never retry even if ExponentialRetryPolicyFilter enabled.

I used it for uploading many files (over 400 files, it took over 2 minutes).
Then AzureBlob returns timeout error like `Errno::ETIMEDOUT: Failed to open TCP connection to xxx.blob.core.windows.net:443 (Connection timed out - connect(2) for "xxx.blob.core.windows.net" port 443).`

I expected retry the request but never retried it.
Because `Azure::Storage::Core::Filter::RetryPolicyFilter` has a feature for check `timeout` ([here](https://github.com/Azure/azure-storage-ruby/blob/v0.15.0/lib/azure/storage/core/filter/retry_filter.rb#L114)) but it rescues only `StandardError` in `Azure::Core::Http::RetryPolicy#call`.

So, I created a pull-request to `azure-core` ([here](https://github.com/Azure/azure-ruby-asm-core/pull/56)) to enable specifying retry-able exceptions. And I want to make this gem be retry-able for timeout errors.

```diff
module Azure::Storage::Core::Filter
  class RetryPolicyFilter < Azure::Core::Http::RetryPolicy
    def initialize(retry_count = nil, retry_interval = nil)
      @retry_count = retry_count
      @retry_interval = retry_interval
      @request_options = {}

+     options = {}
+     options[:retry_exceptions] = [::StandardError, ::Errno::ETIMEDOUT]
+     options[:retry_exceptions] << ::Timeout::Error if defined?(::Timeout::Error)
-     super &:should_retry?
+     super(options, &:should_retry?)
    end
```

**Comment by yaxia** [comment]
@devchick Thanks for raising the issue. I've left comments on your PR. We will release new versions when all comments are addressed.

**Comment by devchick** [comment]
@yaxia, thanks for your reviewing. But I make a mistake specified in the PR. Cloud I close this issue?
