### ISSUE TITLE
invalid options provided for SAS token generate

### ISSUE THREAD

**Issue by fearcraftor** [Azure/azure-storage-ruby#119]
I use azure-storage in combination with Active Storage in a Rails app to store and access to images. I followed all the steps described in rails doc to set up a connection with our Azure storage container.

Upload is alright but I got this error when Rails try to access to the stored blob

Azure::Storage::InvalidOptionsError in ActiveStorage::BlobsController#show

invalid options {:content_disposition=>"inline; filename=\"image.png\"; filename*=UTF-8''image.png", :content_type=>"image/png"} provided for SAS token generate

`azure-storage (0.15.0.preview) lib/azure/storage/core/auth/shared_access_signature_generator.rb:174:in 'generate_service_sas_token'`
`azure-storage (0.15.0.preview) lib/azure/storage/core/auth/shared_access_signature_generator.rb:340:in 'signed_uri'`
`activestorage (5.2.0.rc1) lib/active_storage/service/azure_storage_service.rb:81:in 'block in url'`
`activesupport (5.2.0.rc1) lib/active_support/notifications.rb:168:in 'block in instrument'`
`activesupport (5.2.0.rc1) lib/active_support/notifications/instrumenter.rb:23:in 'instrument'`
`activesupport (5.2.0.rc1) lib/active_support/notifications.rb:168:in 'instrument'`
`activestorage (5.2.0.rc1) lib/active_storage/service.rb:113:in 'instrument'`
`activestorage (5.2.0.rc1) lib/active_storage/service/azure_storage_service.rb:79:in 'url'`
`activestorage (5.2.0.rc1models) active_storage/blob.rb:113:in 'service_url'`
`activestorage (5.2.0.rc1controllers) active_storage/blobs_controller.rb:12:in 'show'`

Did i missed something ?

Thank you in advance

**Comment by yaxia** [comment]
The options you passed into the `Azure::Storage::Core::Auth::SharedAccessSignature.generate_service_sas_token` was not a valid set. Please see the description [here](https://github.com/Azure/azure-storage-ruby/blob/v0.15.0/lib/azure/storage/core/auth/shared_access_signature_generator.rb#L117-L137) for the valid options.

**Comment by fearcraftor** [comment]
Hi

There was a confusing param in Rails Active Storage configuration which lead to this issue. Rails guys have fixed it.

Rails Active Storage set the sas token by itself so there's no need generate it by ourselves.
