### ISSUE TITLE
Using `LinearRetryPolicyFilter` in BlobService throws "ArgumentError: time interval must be positive"

### ISSUE THREAD

**Issue by revathi-murali** [Azure/azure-storage-ruby#121]
Hi,

I am using `LinearRetryPolicyFilter` in my azure blob service and I get the Argument Error `time interval must be positive`. Here is the sample code

```
blob_client= Azure::Storage::Blob::BlobService.new(client: "client-details")
blob_client.with_filter(Azure::Storage::Common::Core::Filter::LinearRetryPolicyFilter.new)

[7] pry(main)> blob_client.get_blob("container-test", "sample.txt")
ArgumentError: time interval must be positive
~/gems/azure-storage-common-1.0.1/lib/azure/storage/common/core/filter/retry_filter.rb:152:in `sleep'
```

**Versions**

Ruby 2.5.1
azure-storage-blob 1.0.1

**Comment by yaxia** [comment]
@revathi-murali Thanks for reporting this issue. This could happen when a request attempt spends longer time than the retry policy's interval. We will fix this in a later release.

**Comment by yaxia** [comment]
It is fixed in the latest release (azure-storage-blob 1.1.0). Please take a try. Thanks.
