### ISSUE TITLE
Connection refused - connect(2) Failed to open TCP connection to ***.blob.core.windows.net:443 

### ISSUE THREAD

**Issue by dcdieci** [Azure/azure-storage-ruby#123]
I use this gem in a rails 5.2 app with active_storage (sidekiq for jobs) and azure as storage provider.
I have a tasks which triggers around 20 upload jobs with 8 files.
In every task one of the jobs is failing.

I assumed that there might be some rate limiting but with this amount of requests I am way below the mentioned limit here

https://blogs.msdn.microsoft.com/windowsazurestorage/2012/11/04/cross-post-windows-azures-flat-network-storage-and-2012-scalability-targets/
> Transactions – Up to 20,000 entities/messages/blobs per second

ruby 2.5.0
`   
      azure-storage (0.15.0.preview)
      azure-core (~> 0.1)
      faraday (~> 0.9)
      faraday_middleware (~> 0.10)
      nokogiri (~> 1.6, >= 1.6.8)`

`2018-06-22T17:59:29.197Z 50351 TID-oul93mp5j WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActiveStorage::AnalyzeJob","queue":"default","args":[{"job_class":"ActiveStorage::AnalyzeJob","job_id":"de6936af-d558-4f48-93fb-3204935146f7","provider_job_id":null,"queue_name":"default","priority":null,"arguments":[{"_aj_globalid":"gid://******/ActiveStorage::Blob/1098"}],"executions":0,"locale":"en"}],"retry":true,"jid":"13b6cc819cb0ad2a635ac4ab","created_at":1529690354.918178,"enqueued_at":1529690354.91857},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActiveStorage::AnalyzeJob\",\"queue\":\"default\",\"args\":[{\"job_class\":\"ActiveStorage::AnalyzeJob\",\"job_id\":\"de6936af-d558-4f48-93fb-3204935146f7\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[{\"_aj_globalid\":\"gid://******/ActiveStorage::Blob/1098\"}],\"executions\":0,\"locale\":\"en\"}],\"retry\":true,\"jid\":\"13b6cc819cb0ad2a635ac4ab\",\"created_at\":1529690354.918178,\"enqueued_at\":1529690354.91857}"}
2018-06-22T17:59:29.197Z 50351 TID-oul93mp5j WARN: Faraday::ConnectionFailed: Failed to open TCP connection to ******.blob.core.windows.net:443 (Connection refused - connect(2) for "******.blob.core.windows.net" port 443)
2018-06-22T17:59:29.197Z 50351 TID-oul93mp5j WARN: .rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:935:in `connect'
.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:909:in `start'
.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:1455:in `request'
.rvm/gems/ruby-2.5.0/gems/rorvswild-1.3.5/lib/rorvswild/plugin/net_http.rb:27:in `block in request_with_rorvswild'
.rvm/gems/ruby-2.5.0/gems/rorvswild-1.3.5/lib/rorvswild/agent.rb:72:in `measure_section'
.rvm/gems/ruby-2.5.0/gems/rorvswild-1.3.5/lib/rorvswild/plugin/net_http.rb:26:in `request_with_rorvswild'
.rvm/gems/ruby-2.5.0/gems/rorvswild-1.3.5/lib/rorvswild/plugin/net_http.rb:18:in `request'
.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:1213:in `get'
.rvm/gems/ruby-2.5.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:85:in `perform_request'
.rvm/gems/ruby-2.5.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:43:in `block in call'
.rvm/gems/ruby-2.5.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
.rvm/gems/ruby-2.5.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:38:in `call'
.rvm/gems/ruby-2.5.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
.rvm/gems/ruby-2.5.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
.rvm/gems/ruby-2.5.0/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
.rvm/gems/ruby-2.5.0/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
.rvm/gems/ruby-2.5.0/gems/azure-core-0.1.14/lib/azure/http_response_helper.rb:27:in `set_up_response'
.rvm/gems/ruby-2.5.0/gems/azure-core-0.1.14/lib/azure/core/http/http_request.rb:149:in `call'
.rvm/gems/ruby-2.5.0/gems/azure-core-0.1.14/lib/azure/core/http/signer_filter.rb:28:in `call'
.rvm/gems/ruby-2.5.0/gems/azure-core-0.1.14/lib/azure/core/http/signer_filter.rb:28:in `call'
.rvm/gems/ruby-2.5.0/gems/azure-core-0.1.14/lib/azure/core/http/http_request.rb:110:in `block in with_filter'
.rvm/gems/ruby-2.5.0/gems/azure-core-0.1.14/lib/azure/core/service.rb:36:in `call'
.rvm/gems/ruby-2.5.0/gems/azure-core-0.1.14/lib/azure/core/filtered_service.rb:34:in `call'
.rvm/gems/ruby-2.5.0/gems/azure-core-0.1.14/lib/azure/core/signed_service.rb:41:in `call'
.rvm/gems/ruby-2.5.0/gems/azure-storage-0.15.0.preview/lib/azure/storage/service/storage_service.rb:62:in `call'
.rvm/gems/ruby-2.5.0/gems/azure-storage-0.15.0.preview/lib/azure/storage/blob/blob_service.rb:62:in `call'
.rvm/gems/ruby-2.5.0/gems/azure-storage-0.15.0.preview/lib/azure/storage/blob/blob.rb:105:in `get_blob'
.rvm/gems/ruby-2.5.0/gems/activestorage-5.2.0/lib/active_storage/service/azure_storage_service.rb:143:in `stream'
.rvm/gems/ruby-2.5.0/gems/activestorage-5.2.0/lib/active_storage/service/azure_storage_service.rb:33:in `block in download'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:170:in `instrument'
.rvm/gems/ruby-2.5.0/gems/activestorage-5.2.0/lib/active_storage/service.rb:118:in `instrument'
.rvm/gems/ruby-2.5.0/gems/activestorage-5.2.0/lib/active_storage/service/azure_storage_service.rb:32:in `download'
.rvm/gems/ruby-2.5.0/gems/activestorage-5.2.0/app/models/active_storage/blob.rb:161:in `download'
.rvm/gems/ruby-2.5.0/gems/activestorage-5.2.0/lib/active_storage/downloading.rb:29:in `download_blob_to'
.rvm/gems/ruby-2.5.0/gems/activestorage-5.2.0/lib/active_storage/downloading.rb:11:in `block in download_blob_to_tempfile'
.rvm/gems/ruby-2.5.0/gems/activestorage-5.2.0/lib/active_storage/downloading.rb:20:in `open_tempfile_for_blob'
.rvm/gems/ruby-2.5.0/gems/activestorage-5.2.0/lib/active_storage/downloading.rb:10:in `download_blob_to_tempfile'
.rvm/gems/ruby-2.5.0/gems/activestorage-5.2.0/lib/active_storage/analyzer/image_analyzer.rb:35:in `read_image'
.rvm/gems/ruby-2.5.0/gems/activestorage-5.2.0/lib/active_storage/analyzer/image_analyzer.rb:21:in `metadata'
.rvm/gems/ruby-2.5.0/gems/activestorage-5.2.0/app/models/active_storage/blob/analyzable.rb:47:in `extract_metadata_via_analyzer'
.rvm/gems/ruby-2.5.0/gems/activestorage-5.2.0/app/models/active_storage/blob/analyzable.rb:29:in `analyze'
.rvm/gems/ruby-2.5.0/gems/activestorage-5.2.0/app/jobs/active_storage/analyze_job.rb:6:in `perform'
.rvm/gems/ruby-2.5.0/gems/activejob-5.2.0/lib/active_job/execution.rb:39:in `block in perform_now'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
.rvm/gems/ruby-2.5.0/gems/rorvswild-1.3.5/lib/rorvswild/agent.rb:79:in `measure_job'
.rvm/gems/ruby-2.5.0/gems/rorvswild-1.3.5/lib/rorvswild/plugin/active_job.rb:12:in `around_perform'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `instance_exec'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
.rvm/gems/ruby-2.5.0/gems/i18n-1.0.1/lib/i18n.rb:284:in `with_locale'
.rvm/gems/ruby-2.5.0/gems/activejob-5.2.0/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `instance_exec'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
.rvm/gems/ruby-2.5.0/gems/activejob-5.2.0/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `block in instrument'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `instrument'
.rvm/gems/ruby-2.5.0/gems/activejob-5.2.0/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
.rvm/gems/ruby-2.5.0/gems/activejob-5.2.0/lib/active_job/logging.rb:46:in `block in tag_logger'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `block in tagged'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:28:in `tagged'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `tagged'
.rvm/gems/ruby-2.5.0/gems/activejob-5.2.0/lib/active_job/logging.rb:46:in `tag_logger'
.rvm/gems/ruby-2.5.0/gems/activejob-5.2.0/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `instance_exec'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:136:in `run_callbacks'
.rvm/gems/ruby-2.5.0/gems/activejob-5.2.0/lib/active_job/execution.rb:35:in `perform_now'
.rvm/gems/ruby-2.5.0/gems/activejob-5.2.0/lib/active_job/execution.rb:24:in `block in execute'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
.rvm/gems/ruby-2.5.0/gems/activejob-5.2.0/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/reloader.rb:73:in `block in wrap'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:83:in `wrap'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/reloader.rb:72:in `wrap'
.rvm/gems/ruby-2.5.0/gems/activejob-5.2.0/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `instance_exec'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:136:in `run_callbacks'
.rvm/gems/ruby-2.5.0/gems/activejob-5.2.0/lib/active_job/execution.rb:22:in `execute'
.rvm/gems/ruby-2.5.0/gems/activejob-5.2.0/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:187:in `execute_job'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:169:in `block (2 levels) in process'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
.rvm/gems/ruby-2.5.0/gems/sidekiq-status-1.0.1/lib/sidekiq-status/server_middleware.rb:42:in `call'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
.rvm/gems/ruby-2.5.0/gems/rorvswild-1.3.5/lib/rorvswild/agent.rb:82:in `measure_job'
.rvm/gems/ruby-2.5.0/gems/rorvswild-1.3.5/lib/rorvswild/plugin/sidekiq.rb:15:in `call'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:168:in `block in process'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:139:in `block (6 levels) in dispatch'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:98:in `local'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:138:in `block (5 levels) in dispatch'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:42:in `block in call'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/reloader.rb:73:in `block in wrap'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/reloader.rb:72:in `wrap'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/rails.rb:41:in `call'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
.rvm/gems/ruby-2.5.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'`

**Comment by dcdieci** [comment]
Hi,
unfortunately the issue is getting worse with the latest rails 5.2.1 version.

"First, by 20 upload jobs with 8 files, do you mean each upload job has 8 files to upload, or 20 upload with a total of 8 files, with each one of them uploading some range of a file."
--> do you mean each upload job has 8 files to upload : yes

"Second, please confirm that you have retry policy applied to your task."
The job is not under my control. The job resides in Rails' active storage gem. Azure storage is being used as an adapter 
https://edgeguides.rubyonrails.org/active_storage_overview.html#microsoft-azure-storage-service

Help would be highly appreciated

**Comment by katmsft** [comment]
We will try to reproduce the issue with given information. Please stay tuned.

**Comment by vinjiang** [comment]
Feel free to let us know if you need further assistance on this issue.

**Comment by equivalent** [comment]
I can confirm this is happening to my application as well :( 


```
Error type: Faraday::ConnectionFailed
Error message: Failed to open TCP connection to xxxxxxxx.blob.core.windows.net:443 (Connection refused - connect(2) for "xxxxxxxx.blob.core.windows.net" port 443)
Where: representations#show
```

Airbrake is getting several of these every day :( 

(sorry I cannot post stack trace due to company privacy )

**Comment by equivalent** [comment]
there are other occurrences of this bug trough out the internet

* https://discuss.elastic.co/t/logstash-with-azure-blob-storage-failed-to-open-tcp-connection/183447/2

**Comment by equivalent** [comment]
I'll just silence the airbrake errors :( nothing else we can do
