### ISSUE TITLE
Nokogiri conflicts between different dependencies 

### ISSUE THREAD

**Issue by ik5** [Azure/azure-storage-ruby#124]
I experience conflict between the `nokogiri `version I use at my project and the requirement for this project.
I've created a [workaround](https://github.com/ik5/azure-storage-ruby/commit/6ddccae8a2fb0f9fc6a1384ae19f559483458c82) for it, to keep supporting both old version and newer versions when needed.

All tests seems to pass after using a newer `nokogiri` version.

**Comment by katmsft** [comment]
The Nokogiri dependency hell has always been a problem that we currently do not have a good solution to. There might be a chance we remove it as dependency in the future but it is not a prioritized item for this client library.
