### ISSUE TITLE
How to enable secure TLS (1.2 or newer version)

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-storage-ruby#129]
As mentioned in https://docs.microsoft.com/en-us/azure/storage/common/storage-security-tls, TLS 1.2 or newer version should be enabled in client side before sending requests to operate Azure Storage service.

Could you please guide me how to enable TLS 1.2 for Azure Storage ruby client? I didn't find the relevant docs.

**Comment by yaxia** [comment]
Please get the latest for the new options exposed.

**Comment by andyliuliming** [comment]
@yaxia updated the options in our code. thanks!
