### ISSUE TITLE
 License file is missing

### ISSUE THREAD

**Issue by Quasilyte** [Azure/azure-storage-ruby#134]
This repository misses the license file.
The severity of that varies from project to project, but my goal here is to attract some attention.

If it's not a problem, this issue can be closed.

I'm leaving it here just in case: https://help.github.com/articles/adding-a-license-to-a-repository/.

Thanks.

**Comment by yaxia** [comment]
@Quasilyte Thanks for your suggestion.
As we release several gem packages from this repository (azure-storage-common, azure-storage-blob, azure-storage-queue, azure-storage-file and azure-storage-table),  we put the license file in each package root.
azure-storage-common: https://github.com/Azure/azure-storage-ruby/blob/master/common/LICENSE.txt
azure-storage-blob: https://github.com/Azure/azure-storage-ruby/blob/master/blob/LICENSE.txt
azure-storage-queue: https://github.com/Azure/azure-storage-ruby/blob/master/queue/LICENSE.txt
azure-storage-file: https://github.com/Azure/azure-storage-ruby/blob/master/file/LICENSE.txt
azure-storage-table: https://github.com/Azure/azure-storage-ruby/blob/master/table/LICENSE.txt
