### ISSUE TITLE
How to use with active-storage?

### ISSUE THREAD

**Issue by dennisjbell** [Azure/azure-storage-ruby#143]
Active Storage states that to use Azure, include the azure-storage gem.  That gem was last updated in November 2017, and is on v0.15.0-preview.  The homepage for that gem is listed as this github repo (see https://rubygems.org/gems/azure-storage/versions/0.15.0.preview).

The releases for this repo are all broken out to blob, table, common and queue.  How can the azure-storage gem be reconstituted from this?  Is there another way to use these libraries with Active Record?

**Comment by yaxia** [comment]
The change of splitting libraries for each service was introduced in the GA release, described at #107.

The Active Storage only uses [block blob](https://github.com/rails/rails/blob/v6.0.0.beta3/activestorage/lib/active_storage/service/azure_storage_service.rb). There is no change for block blob between the v0.15-preview and the v1.x version. It is fine to keep 0.15-preview in Active Storage. 

To use the new blob gem, I think it is best to send a PR to the Rails repo to update the library.
