### ISSUE TITLE
Multiple Download blobs

### ISSUE THREAD

**Issue by khushbugoyal** [Azure/azure-storage-ruby#146]
I am using Ruby script and want to have some way to download multiple files at once from a container with matching some string in their names either in zip way or in a folder.
I have around 2500 files to download at once and as I have to go through loop for so many files, the process get halted in between and get error 'Connection reset by peer - SSL_connect'.
Please help me here. It is really needed for me.

**Comment by khushbugoyal** [comment]
Is there any way to do so?

**Comment by katmsft** [comment]
In order to reproduce the issue, can you please share the code snippet that you used to download the files?

**Comment by vinjiang** [comment]
Feel free to let us know if further assistance required.
