### ISSUE TITLE
Unable to generate signed URL for blob with space in name 

### ISSUE THREAD

**Issue by yxnyxnyxnyxnyxnyxn** [Azure/azure-storage-ruby#148]
I tried to encode the blob name -> signed_url 
Server failed to authenticate the request. 
Signature did not match.

**Comment by katmsft** [comment]
What authentication are you using, is it SAS authentication?

**Comment by yxnyxnyxnyxnyxnyxn** [comment]
Yes I’m using SAS

**Comment by yxnyxnyxnyxnyxnyxn** [comment]
Plz help! please

**Comment by katmsft** [comment]
Hi,

I tried to reproduce with below code but was able to successfully create the blob. Can you tell me what am I missing?
```
require 'azure/storage/blob'
require 'concurrent'

# Setup a specific instance of an Azure::Storage::Blob::BlobService
sas_builder = Azure::Storage::Common::Core::Auth::SharedAccessSignature.new('katrubytest', 'XXX')
blob_client = Azure::Storage::Blob::BlobService.create(default_endpoints_protocol: 'http', storage_account_name: 'katrubytest', storage_access_key: 'XXX')
container_name = 'connectionresetcontainer11'
blob_name = 'blob   name'
sas_token = sas_builder.generate_service_sas_token "#{container_name}/#{blob_name}", service: "b", resource: "b", permissions: "racwdl"
connection_string = "BlobEndpoint=http://katrubytest.blob.core.windows.net;SharedAccessSignature=#{sas_token}"

client = Azure::Storage::Blob::BlobService::create_from_connection_string connection_string

# client.create_container container_name
client.create_page_blob container_name, blob_name, 1024


```

**Comment by yxnyxnyxnyxnyxnyxn** [comment]
I'm able to create the blob with space in name, but i cannot generated a sharedUrl for the blob using **signed_uri** method. 
example code: 
blob_name = encode('blob name')
#blob_name = "blob%20name"
blob_url = "https://#{storage_name}.blob.core.windows.net/#{container_name}/#{blob_name}"
shared_url = Azure::Storage::Core::Auth::SharedAccessSignature.new(storage_name, storage_key).signed_uri(blob_url)

the example code will return shared_url for "blob%20name" not "blob name"

**Comment by katmsft** [comment]
Hi, Can you try the below code to generate the SAS for use instead of using the signed_uri?
```
      connection_string = "BlobEndpoint=https://#{SERVICE_CREATE_OPTIONS()[:storage_account_name]}.blob.core.windows.net;SharedAccessSignature=#{sas_token}"
      client = Azure::Storage::Blob::BlobService::create_from_connection_string connection_string
```

**Comment by vinjiang** [comment]
Please let us know if you still have questions.

**Comment by itayariel** [comment]
Hi, we also experience this issue, signing a file with a space in its name.
We found that `generate_service_sas_token ` should receive the file name decoded without url encoding
