### ISSUE TITLE
Chunk big blobs

### ISSUE THREAD

**Issue by yaxia** [Azure/azure-storage-ruby#15]
Migrate from the Azure SDK: https://github.com/Azure/azure-sdk-for-ruby/issues/212
.
As reported here: http://stackoverflow.com/questions/23567724/ruby-azure-blob-storage-requestbodytoolarge, SDK doesn't split files bigger than 64M for API supported upload.

Currently, solutions are available using different gems: 
•Ruby: https://github.com/dmichael/azure-contrib 
•UI: https://github.com/Sology/azure_direct_upload 

This should be a part of SDK, imho.

**Comment by aufi** [comment]
+1 for have it as part of SDK

**Comment by yaxia** [comment]
We have this feature in the GA version. However, we don't have much optimization for doing this in parallel yet. If you are uploading many GB of data, I'd suggest to implement your own concurrent calls of `put_blob_block` and `commit_blob_blocks` as an end.

**Comment by yaxia** [comment]
@PabloK Here is an option before we having a single API to support this in the library:

- Call `Azure::Storage::Blob::put_blob_block` and `Azure::Storage::Blob::commit_blob_blocks` to upload one big blob.

Please refer to what we have done in the [Fog](https://github.com/fog/fog-azure-rm/blob/master/lib/fog/azurerm/requests/storage/multipart_save_block_blob.rb)
