### ISSUE TITLE
Dependency problem with faraday 1.0.0

### ISSUE THREAD

**Issue by jlavanchy** [Azure/azure-storage-ruby#154]
Hello, 

I created an issue related to azure-core because of a problem related to a dependency between Faraday 1.0.0 and azure-core (https://github.com/Azure/azure-ruby-asm-core/issues/70). 

We are using azure-storage-blob with Chef in order to download resources from Azure. The last version of Chef (15.8.23) ship with the last version of Faraday (1.0.0) released in January. 

This is causing an issue as azure-storage-blob gem depends on azure-core gem, which itself depends on faraday ~> 0.9. Since faraday is in version 1.0.0, this cause a dependency problem leading chef to crash. 

For the time being, we are using the previous minor version of Chef on our end which is using faraday 0.17.1. 

From what @yaxia told me on the original issue report, azure-core will not be updated and everything will be transfert into this github repo. This is why I am creating another issue here. 

Could you please review and try to fix this issue? Thanks in advance! 

Julien.

**Comment by yaxia** [comment]
Thanks for reporting it. We will upgrade it in a later release.

**Comment by katmsft** [comment]
This issue is addressed in azure-storage-common v2.0.1, check it out and thanks for reporting.
