### ISSUE TITLE
Azure::Core::Http::HTTPError: AuthenticationFailed (403): Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

### ISSUE THREAD

**Issue by k4l1mi5t** [Azure/azure-storage-ruby#163]
I have issues interacting with the blobservice, each request ends up in the following error:

Azure::Core::Http::HTTPError: AuthenticationFailed (403): Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

Using the following code with sas: 

```
    access_token = '?sv=2019-02-02&ss=b&srt=sco&sp=rwdlac&se=2020-05-30T23:27:31Z&st=2020-04-27T15:27:31Z&spr=https,http&sig=xxx'

    token_credential = Azure::Storage::Common::Core::TokenCredential.new access_token
    token_signer = Azure::Storage::Common::Core::Auth::TokenSigner.new token_credential

    azure_client = Azure::Storage::Blob::BlobService.new(storage_account_name: "xxx", signer: token_signer)

    azure_client.create_block_blob('xxx', 'test.jpg', '/Users/tester/Desktop/test.jpg')
```

There seems to be a common issue with the timezone using the api, I'm in utc+1 berlin and made sure when creating the sas that the correct timezone was selected.

**Comment by katmsft** [comment]
Besides the timezone, we also retrieve the date from the system and send it to the service.
However, I'm not in UTC timezone but I don't have any problem using the SDK.
Can you please tell me if you are using the SAS created with the Ruby SDK?

**Comment by k4l1mi5t** [comment]
The sas token is created from the azure portal, since this is how our partner does it and we wanted to test against that. It worked neither with the one created from our partner nor from my own created one. 

We found a working solution with the sas connection string:

common_client = Azure::Storage::Common::Client.create_from_connection_string(@azure_connection_string)
azure_client = Azure::Storage::Blob::BlobService.new(client: common_client)

Still not sure how this should work with the advertised way, but I will leave this here for anyone hitting the same issue

**Comment by sandeep-svg** [comment]
hi
am getting same error while am generating access token with managed identity enabled and my production server working perfectly but after sometime it's automatically throwing this error

after restarting the service again it's working like this it's happening repeatedly and
am using code as below

## Access Token

Please refer to the below links for obtaining an access token:
* [Authenticate with Azure Active Directory](https://docs.microsoft.com/en-us/rest/api/storageservices/authenticate-with-azure-active-directory)
* [Getting a MSI access token](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-linux-vm-access-storage#get-an-access-token-and-use-it-to-call-azure-storage)

```ruby
require "azure/storage/common"

access_token = <your initial access token>

# Creating an instance of `Azure::Storage::Common::Core::TokenCredential`
token_credential = Azure::Storage::Common::Core::TokenCredential.new access_token
token_signer = Azure::Storage::Common::Core::Auth::TokenSigner.new token_credential
blob_token_client = Azure::Storage::Blob::BlobService.new(storage_account_name: <your_account_name>, signer: token_signer)

# Refresh internal is 50 minutes
refresh_interval = 50 * 60
# The user-defined thread that renews the access token
cancelled = false
renew_token = Thread.new do
  Thread.stop
  while !cancelled
    sleep(refresh_interval)

    # Renew the access token here

    # Update the access token to the credential
    token_credential.renew_token <new_access_token>
  end
end
sleep 0.1 while renew_token.status != 'sleep'
renew_token.run

**Comment by avivansh** [comment]
@sandeep-svg  did you figure out a way for this? I am also facing the same issue. Also, could you please share the logic of how you are generating the access token?
