### ISSUE TITLE
Dependency problem with nokogiri 1.10.9 and Ruby 2.7.0

### ISSUE THREAD

**Issue by jlavanchy** [Azure/azure-storage-ruby#165]
Hello, 

We have an issue with the gem azure-storage-common. This gems works fine on Ruby 2.6.X (Chef  Infra 15). 

But when using Ruby 2.7.0 (built in on Chef Infra 16), the nokogiri version 1.10.9 does not officially support this version of Ruby ....

The new version of nokogiri 1.11.0.rc2 is compatible. But based on the dependency of Azure storage common gem, only ~> 1.10.4 is used. 

Could the version of nokogiri be bumped up? 

Thanks. 

Julien.

**Comment by yaxia** [comment]
Yes, we will bump up to the Ruby 2.7 compatible version. Please stay tuned.

**Comment by jlavanchy** [comment]
Any new on this? 

Julien.

**Comment by yaxia** [comment]
@katmsft is working on the release.

> Any new on this?
> 
> Julien.

**Comment by katmsft** [comment]
This is fixed in 2.0.1/2.0.2 release, check it out!
