### ISSUE TITLE
Support for fog

### ISSUE THREAD

**Issue by muichkine** [Azure/azure-storage-ruby#17]
Do you plan on integrating azure storage to [fog](https://github.com/fog/fog) ?

**Comment by yaxia** [comment]
We are investigating, please stay tuned.

**Comment by allaire** [comment]
Would be awesome!

**Comment by yaxia** [comment]
We've started the work on https://github.com/fog/fog-azure-rm. You can track our status from there.

**Comment by yaxia** [comment]
The provider has been released, please take a look at https://github.com/fog/fog-azure-rm/blob/master/lib/fog/azurerm/docs/storage.md. Thanks.
