### ISSUE TITLE
Error when creating a storage client

### ISSUE THREAD

**Issue by pchowdhry** [Azure/azure-storage-ruby#19]
When executing client = Azure::Storage.create(:storage_account_name => "###", :storage_access_key => "###") 

receiving

Azure::Storage::InvalidOptionsError: options provided are not valid set: {}

Setup is working...

Thanks

-pankaj

**Comment by yaxia** [comment]
Thanks. We are investigating this issue.

**Comment by vr4b4c** [comment]
@pechyony I hit the same wall with the most basic script. I managed to bypass the problem with global ENV settings(only thing to note, ENVs should be set before you ```require 'azure/storage'```)
```ruby
# my_client.rb
ENV['AZURE_STORAGE_ACCOUNT'] = 'account'
ENV['AZURE_STORAGE_ACCESS_KEY'] = 'access-key'

require 'azure/storage'
...
```
or export them before running the script.

**Comment by pchowdhry** [comment]
thanks @vr4b4c  That worked for me. It looks like the gem isn;t picking up the code based config, and need the env variables. If I get some time I'll dive into the gem and see if I can track down the issue.

**Comment by yaxia** [comment]
It is fixed in 0.10.2.preview. Please take a try, thanks.

**Comment by pchowdhry** [comment]
worked for me.

Thanks

**Comment by mydiemho** [comment]
I'm seeing this problem in 0.12.1.preview
