### ISSUE TITLE
Illegal use of Content-Encoding

### ISSUE THREAD

**Issue by slumos** [Azure/azure-storage-ruby#20]
This client still conflating Content-Encoding with character-set encoding, here:

https://github.com/Azure/azure-storage-ruby/blob/fdb2c6f15fea6f3e3e4cb2721c6af8d1f39e8592/lib/azure/storage/blob/blob_service.rb#L47

Valid values for Content-Encoding are, e.g. 'gzip', 'compress', etc. E.g.

```
Content-Encoding: gzip
```

The character-set encoding is found at the end of the Content-Type header, e.g.

```
Content-Type: application/json; charset=utf-8
```

My colleague @thomas-schreiter filed a PR against the old SDK here: https://github.com/Azure/azure-storage-ruby/blob/fdb2c6f15fea6f3e3e4cb2721c6af8d1f39e8592/lib/azure/storage/blob/blob_service.rb#L47.

**Comment by yaxia** [comment]
@slumos , @thomas-schreiter could you please submit the PR to this repo? Thanks.

**Comment by yaxia** [comment]
It is also reported in #49 .
Fixed in https://github.com/Azure/azure-storage-ruby/pull/58
