### ISSUE TITLE
Issue while listing page blob ranges

### ISSUE THREAD

**Issue by pcibraro** [Azure/azure-storage-ruby#30]
I am not being able to get the list method for page blob ranges to work. I am not sure if it's a really a bug or I am using this method incorrectly. Apologies if I am using this incorrectly
```
page_data = 512.times.map { [*'0'..'9', *'a'..'z'].sample }.join
blob_service.put_blob_pages(container_name, blob_name, 0, 511, page_data, {})
pages = blob_service.list_page_blob_ranges(container_name, blob_name, { :start_range => 0, :end_range => 511})
```
I expected to get at least one page with the data I just pushed, but I am not seeing the data in the first element of the returned array.

**Comment by vinjiang** [comment]
@yaxia, please take a look.

**Comment by yaxia** [comment]
@pcibraro the `list_page_blob_ranges` function only lists the page ranges without any blob content in the message body. So you may only get: 
``` html
<?xml version="1.0" encoding="utf-8"?><PageList><PageRange><Start>0</Start><End>511</End></PageRange></PageList>
```

If you want to fetch the data in the range, you might want to call:
``` ruby
blob_service.get_blob container_name, blob_name, {:start_range =>0, :end_range => 511}
```

**Comment by vinjiang** [comment]
We are closing this issue with no further feedback. Feel free to let us know if you have any further questions on this issue.
