### ISSUE TITLE
TableService.new does not work

### ISSUE THREAD

**Issue by airmanx86** [Azure/azure-storage-ruby#36]
Using 0.10.2, follow the readme and fail when calling `TableService.new`
Storage name and key were set correctly in env.
```
require "azure/storage"
tables = Azure::Storage::Table::TableService.new
```
The comments suggest that we need to setup, why not just include the code?
```
require "azure/storage"
Azure::Storage.setup
tables = Azure::Storage::Table::TableService.new
```

**Comment by yaxia** [comment]
Thanks for the catching. We will update it.

**Comment by yaxia** [comment]
Updated.
