### ISSUE TITLE
0.10.2.preview generates bad blob sas-url 

### ISSUE THREAD

**Issue by mbnshtck** [Azure/azure-storage-ruby#38]
I am using 0.10.1.preview for some time, tried to move to 0.10.2.preview, and found that the blob sas-url generated is different. The SAS token is shorter, and has a different &sv value (version date). The application that get the url fails to open the blob with this url.

**Comment by yaxia** [comment]
Thanks for raising the issue. We will fix it soon.

**Comment by yaxia** [comment]
Fixed in 0.11.0.preview.
