### ISSUE TITLE
Set Content-Disposition (content_disposition) for direct download?

### ISSUE THREAD

**Issue by scande3** [Azure/azure-storage-ruby#39]
I'm having some difficulty figuring out how set the Content-Disposition in Ruby so that I can set a "friendly download filename". Upon retrieval of anything I upload, I only get the following non-standard header back (sample url: https://dcpreservation.blob.core.windows.net/production-master/bpl-dev_j6731378s ):

`x-ms-meta-Content_disposition: attachment; filename=myfile.tif`

The most complex example of setting this property via two ways on my end is:

    metadata = { :content_disposition => 'attachment; filename=myfile.tif' }
    options = { :metadata => metadata, :content_type => 'image/tif', :content_disposition => 'attachment; filename=myfile.tif' }
    blob = azure_blob_service.create_block_blob(container.name, 'bpl-dev_j6731378s', content, options)

Am I doing something incorrect? Is there a separate way to set the Content-Disposition header for direct downloads that may be outside the scope of this Ruby library? Or is the only way to make a file available for download with a custom filename to have my application act as an intermediate layer?

**Comment by yaxia** [comment]
@scande3 You got the `x-ms-meta-Content_disposition` header because you set the metadata which returned in the header of `x-ms-<meta-name>: value`. However, it should not prevent you from setting the content-disposition property.

```ruby
options = { content_type: 'image/tif', content_disposition: 'attachment; filename=myfile.tif' }
blob = azure_blob_service.create_block_blob(container.name, 'bpl-dev_j6731378s', content, options)
```

If the blob already exists, you can set its properties by calling `set_blob_properties`

```ruby
options = { content_type: 'image/tif', content_disposition: 'attachment; filename=myfile.tif' }
blob = azure_blob_service.set_blob_properties(container.name, 'bpl-dev_j6731378s', options)
```

The above code works for me. I am not sure why the sample URL (https://dcpreservation.blob.core.windows.net/production-master/bpl-dev_j6731378s) doesn't work as expected. Could you try to call `get_blob_properties` to check whether the `content-disposition` property is successfully set?

**Comment by scande3** [comment]
@yaxia - I ran both of your samples. The first to use "set_blob_properties" on the existing item that did not have an effect. To ensure it wasn't some browser caching issue, I then copied + pasted your code to create a blob but added a "3" at the end (so the file is now https://dcpreservation.blob.core.windows.net/production-master/bpl-dev_j6731378s3 ). The response still lacked a Content-Disposition. The exact commands run were:

     2.2.1 :052 > options = { content_type: 'image/tif', content_disposition: 'attachment; filename=myfile.tif' }
     => {:content_type=>"image/tif", :content_disposition=>"attachment; filename=myfile.tif"} 
     2.2.1 :055 > blob = azure_blob_service.create_block_blob(container.name, 'bpl-dev_j6731378s3', content, options)
     => #<Azure::Blob::Blob:0x00000005dabf38 @properties={:last_modified=>"Wed, 17 Aug 2016 14:50:48 GMT", :etag=>"\"0x8D3C6ADE02813A9\"", :lease_status=>nil, :lease_state=>nil, :lease_duration=>nil, :content_length=>nil, :content_type=>nil, :content_encoding=>nil, :content_language=>nil, :content_md5=>"kq3F+f3PXH6KZSwJfdsCag==", :cache_control=>nil, :blob_type=>nil, :copy_id=>nil, :copy_status=>nil, :copy_source=>nil, :copy_progress=>nil, :copy_completion_time=>nil, :copy_status_description=>nil}, @metadata={}, @name="bpl-dev_j6731378s3">

"get_blob_properties" doesn't show a "content_disposition" property for either of the files. For the original one ('bpl-dev_j6731378s'), it's properties are:

    2.2.1 :056 > blob = azure_blob_service.get_blob_properties(container.name, 'bpl-dev_j6731378s')
     => #<Azure::Blob::Blob:0x00000006db5410 @properties={:last_modified=>"Wed, 17 Aug 2016 14:48:07 GMT", :etag=>"\"0x8D3C6AD807ED878\"", :lease_status=>"unlocked", :lease_state=>"available", :lease_duration=>nil, :content_length=>57062536, :content_type=>nil, :content_encoding=>nil, :content_language=>nil, :content_md5=>nil, :cache_control=>nil, :blob_type=>"BlockBlob", :copy_id=>nil, :copy_status=>nil, :copy_source=>nil, :copy_progress=>nil, :copy_completion_time=>nil, :copy_status_description=>nil, :accept_ranges=>0}, @metadata={"content_disposition"=>"attachment; filename=myfile.tif"}, @name="bpl-dev_j6731378s", @snapshot=nil> 

For the newly created one ('bpl-dev_j6731378s3'), its properties are:

    2.2.1 :057 > blob = azure_blob_service.get_blob_properties(container.name, 'bpl-dev_j6731378s3')
     => #<Azure::Blob::Blob:0x00000006d7c868 @properties={:last_modified=>"Wed, 17 Aug 2016 14:50:48 GMT", :etag=>"\"0x8D3C6ADE02813A9\"", :lease_status=>"unlocked", :lease_state=>"available", :lease_duration=>nil, :content_length=>57062536, :content_type=>"image/tif", :content_encoding=>"ascii-8bit", :content_language=>nil, :content_md5=>"kq3F+f3PXH6KZSwJfdsCag==", :cache_control=>nil, :blob_type=>"BlockBlob", :copy_id=>nil, :copy_status=>nil, :copy_source=>nil, :copy_progress=>nil, :copy_completion_time=>nil, :copy_status_description=>nil, :accept_ranges=>0}, @metadata={}, @name="bpl-dev_j6731378s3", @snapshot=nil>

Any additional help would be appreciated. Thanks!

**Comment by yaxia** [comment]
@scande3 If I guess right, you are using the `azure` gem instead of the `azure-storage` gem.
In the `azure` gem, you need set the property with the options `blob_content_type` and `blob_content_disposition`:
```ruby
options = { :blob_content_type => 'image/tif', :blob_content_disposition => 'attachment; filename=myfile.tif' }
blob = azure_blob_service.create_block_blob(container.name, 'bpl-dev_j6731378s', content, options)
```
Reference: https://github.com/Azure/azure-sdk-for-ruby/blob/asm/lib/azure/blob/blob_service.rb#L949

I would suggest you to move to the `azure-storage` gem for the Azure Storage operation. It has a lot of improvements in the recent releases.

**Comment by scande3** [comment]
@yaxia - Thanks so much! Can confirm that I had been using the `azure` gem (had assumed it included this as a dependency for some reason...). The code sample you work functions there correctly.

I'm unable to duplicate success in '0.10.2.preview' of `azure-storage` though. I keep receiving the following authentication error trying to create the blob: `Azure::Core::Http::HTTPError: AuthenticationFailed (403): Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.`

Full code (credentials work with the Azure gem - tested them again to ensure no credential copy error):

    Azure::Storage.setup(:storage_account_name => "<my account>", :storage_access_key => "<my storage key>")
    options = { content_type: 'image/tif', content_disposition: 'attachment; filename=myfile.tif' }
    content = File.open("/home/bluewolf/Desktop/to_ingest/final/sample/11_04_000001.tiff", "rb") { |file| file.read }
    azure_blob_service = Azure::Storage::Blob::BlobService.new
    blob = azure_blob_service.create_block_blob(container.name, 'bpl-dev_j6731378s4', content, options)

Will keep an eye on this gem and try out future releases then. Closing this and thanks again for the help!
