### ISSUE TITLE
list_blobs doesn't work at all when delimiter is specified

### ISSUE THREAD

**Issue by makhdumi** [Azure/azure-storage-ruby#41]
When `list_blobs` is called with a delimiter, e.g. `/`, it does not return any results despite the server returning a valid response.

[This part](https://github.com/Azure/azure-storage-ruby/blob/fdb2c6f15fea6f3e3e4cb2721c6af8d1f39e8592/lib/azure/storage/blob/serialization.rb#L115) in blob_enumeration_results_from_xml doesn't check for `(xml > "Blobs") > "BlobPrefix"` which is what the server returns when `delimiter` is specified.

If this is actually an issue, it's very surprising since this use case of `list_blobs` is extremely common and even the default in other client libraries. It's needed when trying to traverse a pseudo-directory structure in blob storage, otherwise, results are returned "flat" or "recursive," and with thousands of blobs, it's not usable.

See [here](https://github.com/Azure/azure-storage-net/blob/68c3ee55a3a6f62a0159cea58005d3fe027312a8/Lib/ClassLibraryCommon/Blob/CloudBlobContainer.cs#L2770) the .NET client, where it uses a delimiter (`/`) by default (`useFlatBlobListing` is false by default).

I would submit a pull request (after signing the  CLA) but don't know how you want the results of this returned, given that the results don't represent actual Blobs, just prefixes.

**Comment by makhdumi** [comment]
Here are some potential changes to fix this:
https://github.com/makhdumi/azure-storage-ruby/commit/ac45844db64eed7d5b0863a851612b999cc5238d

**Comment by yaxia** [comment]
@makhdumi Thanks for raising the issue. If you are going to submit a fix, we expect the result is still an array. This array can hold two kinds of objects, one is Azure::Storage::Blob, the other one is a string whose value is the prefix value.

**Comment by makhdumi** [comment]
@yaxia I've submitted pull request with the fix, https://github.com/Azure/azure-storage-ruby/pull/42

**Comment by vinjiang** [comment]
Thanks for your contribution, it's now in latest release.
