### ISSUE TITLE
Container.get_container_properties should raise an exception when the container does not exist

### ISSUE THREAD

**Issue by gossion** [Azure/azure-storage-ruby#47]
Currently when the container does not exist, Container.get_container_properties return properties: 
{:last_modified=>nil, :etag=>nil, :lease_status=>nil, :lease_state=>nil, :lease_duration=>nil}.

It should raise an exception like what it does in azure-sdk-for-ruby.

**Comment by yaxia** [comment]
@gossion Could you please share your code of creating the blob client? I cannot reproduce this issue. I got the exception as expected:
 ```ruby
client = Azure::Storage::Client.create
blob_client = client.blob_client
properties = blob_client.get_container_properties 'nonexistingcontainer'
```
Result:
```
>/2.2.0/gems/azure-core-0.1.4/lib/azure/core/http/http_request.rb:147:in `call': ContainerNotFound (404): The specified container does not exist. (Azure::Core::Http::HTTPError)
```

**Comment by gossion** [comment]
Thanks, @yaxia 

Our code is at this [link](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/src/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb#L198-L210)

However, I do see one difference: in our code the client is initiated by client.`blobClient` ([code](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/src/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb#L295)) but in your example  it is initiated by client.`blob_client`. what are differences between these two methods?

**Comment by yaxia** [comment]
The change was introduced in the [commit](https://github.com/Azure/azure-storage-ruby/commit/c7ad558564080dc35baf2e0bcf8dce24134220d2) to follow the Ruby naming convention.

Could you please update the latest version and try again? (There is an update in the azure-core gem as well)

**Comment by gossion** [comment]
sure, will try.

**Comment by gossion** [comment]
Hi yaxia, with azure-storage-ruby 0.11.0-preview, the issue is gone.  thanks.

I will close this issue.
