### ISSUE TITLE
blob download using the ruby azure-storage gem is failing due to 'unknown encoding name' ArgumentError

### ISSUE THREAD

**Issue by JoeNunnelley** [Azure/azure-storage-ruby#49]
here is what I am doing
# blob service initialization

```
Azure::Storage::setup(:storage_account_name => @account_name, 
                      :storage_access_key => @access_key)
@blob_service = Azure::Storage::Blob::BlobService.new
```

...
# attempt to download a blob where the deconstructed[:blob_name] is the name of the blob.

blob_factual,` content = @blob_service.get_blob(container_name, deconstructed[:blob_name], { :timeout => timeout })
File.open("#{deconstructed[:target_dir]}/#{deconstructed[:blob_name]}", "wb") { |f| f.write(content) }

I hit the following error: 

WARN: Unable to download: 00094811-D064-41D1-9F98-5BF3C24F05FC due to argument error.
unknown encoding name - application/octet-stream
/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/azure-storage-0.11.0.preview/lib/azure/storage/blob/blob_service.rb:63:in `force_encoding'\n/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/azure-storage-0.11.0.preview/lib/azure/storage/blob/blob_service.rb:63:in`call'\n/usr/local/var/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/azure-storage-0.11.0.preview/lib/azure/storage/blob/blob.rb:89:in `get_blob'\nmove_blobs_azure.rb:63:in`download_blob'\nmove_blobs_azure.rb:49:in `block in get_blobs_from_container'\nmove_blobs_azure.rb:45:in`each'\nmove_blobs_azure.rb:45:in `get_blobs_from_container'\nmove_blobs_azure.rb:138:in`block in <main>'\nmove_blobs_azure.rb:135:in `each'\nmove_blobs_azure.rb:135:in`<main>'

it appears to be failing at a call to .force_encoding(...)

**Comment by yaxia** [comment]
It looks the value in the `response.headers['content-encoding']` header is `application/octet-stream` which is a content-type value. It is not supposed to happen. I will dig more on the root cause.

**Comment by yaxia** [comment]
I am evaluating the PR for the fix: https://github.com/Azure/azure-storage-ruby/pull/52. Stay tuned~
