### ISSUE TITLE
PUBLIC NOTICE: Azure Storage Ruby Client Library Update

### ISSUE THREAD

**Issue by yaxia** [Azure/azure-storage-ruby#5]
We are pleased to announce an update to our Ruby client library for Storage. 
We received storage service feature support requests and requests to fix a few issues in the Azure SDK for Ruby. To address your requests, we are working towards supporting new features released on the service and bring the Ruby Storage library to parity with the newest endpoint. Some of these changes include AppendBlob support, File service support, replacing AtomPub with JSON in table, Account SAS, improved response parsing and many other small features and API updates.

To support the above, we will need to make some breaking changes. The first round of changes will be the largest and will bring the library up to the Feb 2015 service version. We will focus on the storage features now present in this repository and release as the azure-storage package on [RubyGems](https://rubygems.org/).  All of this work is being done in the dev branch and we will be maintaining [ChangeLog](https://github.com/Azure/azure-storage-ruby/blob/master/ChangeLog.txt) and [BreakingChanges](https://github.com/Azure/azure-storage-ruby/blob/master/BreakingChanges.txt) files so you can see a summary of what’s happening. Note that this branch should not be considered stable!

After bringing the library up to the latest version, we will then begin adding client-side improvements. We are considering items such as built-in MD5 calculation, automatically following continuation tokens on list APIs, improved queue message encoding support, and many others, including improvements the community suggests. So please provide us your feedback on what you would like to  see implemented in the Ruby Storage client library.

We’d love to hear from you!

Thanks,
The Azure Storage Team

**Comment by tamaloa** [comment]
How about releasing a stable version at some time? Depending on a preview gem version for something critical as storage just does not feel good ;)

**Comment by yaxia** [comment]
@tamaloa We have released our GA version. Please take a try. Your feedback is appreciated.
