### ISSUE TITLE
Relax JSON 1.x 

### ISSUE THREAD

**Issue by toddysm** [Azure/azure-storage-ruby#55]
The library has a hard dependency on the 1.x JSON gem, which breaks newer gems that are using 2.x JSON. Can the dependency be relaxed or removed from the gemspec?

**Comment by yaxia** [comment]
Thanks for your feedback. We are evaluating this requirement and will update to you soon.

**Comment by yaxia** [comment]
We will move to JSON 2.x in a later release, please stay tuned. Thanks.

**Comment by yaxia** [comment]
We removed the constrain in 0.11.4. Please take a try. Thanks.

**Comment by toddysm** [comment]
Works for us now.
