### ISSUE TITLE
SHOULD NOT retry when Azure returns 404 NOT_FOUND

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-storage-ruby#56]
```
blob_client.get_blob_properties(container_name, name, options)
```

When I tried above command for a non-exist blob, I got the result after a long time. But if I comment below code, I got the result very soon. It seems like that sdk retries when receiving 404. 

```
blob_client.with_filter(Azure::Storage::Core::Filter::ExponentialRetryPolicyFilter.new)
```

**Comment by yaxia** [comment]
Looking, will update to you soon.

**Comment by AbelHu** [comment]
@yaxia , do you have any status update on this issue?

**Comment by yaxia** [comment]
I fixed it in https://github.com/yaxia/azure-storage-ruby/tree/dev and it is now in review and test, you can try it or wait for the official release. Thanks.
