### ISSUE TITLE
Wrong link in the comment of list_containers

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-storage-ruby#57]
The link in this [line](https://github.com/Azure/azure-storage-ruby/blob/master/lib/azure/storage/blob/blob_service.rb#L107) should be https://msdn.microsoft.com/en-us/library/azure/dd179352.aspx

**Comment by yaxia** [comment]
The original link is correct, it intends to link to the C# identifier rules.
  
 > Beginning with that version, all metadata names must adhere to the naming, all metadata names must adhere to the naming conventions for C# identifiers. 
> See: http://msdn.microsoft.com/en-us/library/aa664670(VS.71).aspx

**Comment by AbelHu** [comment]
I see. But the link is different from others, for example, the [link](https://github.com/Azure/azure-storage-ruby/blob/master/lib/azure/storage/blob/blob_service.rb#L163) for `require_lease`, the [link](https://github.com/Azure/azure-storage-ruby/blob/master/lib/azure/storage/blob/blob_service.rb#L223) for `renew_lease`, etc.

**Comment by yaxia** [comment]
Agree it is kind of confusing. When there is no special context, the link is for the REST API, otherwise it explains as the context.

**Comment by AbelHu** [comment]
It is better to add the [link](https://msdn.microsoft.com/en-us/library/azure/dd179352.aspx) to the REST API as others and then add the [link](http://msdn.microsoft.com/en-us/library/aa664670(VS.71).aspx) to the context :)
