### ISSUE TITLE
Azure checks the MD5 hash when 'Content-MD5' is not specified.

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-storage-ruby#64]
According to the [doc](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/put-blob), Azure storage service only checks the hash that has arrived with the one that was sent when `Content-MD5` is specified.
But when I tried to call `create_block_blob` with a header contains an invalid MD5 hash in `x-ms-blob-content-md5` but does not contain `Content-MD5`, Azure returned below error.

```
<Code>Md5Mismatch</Code><Message>The MD5 value specified in the request did not match with the MD5 value calculated by the server. </Message>
```

**Comment by yaxia** [comment]
I will check the server behavior. Please stay tuned.

**Comment by yaxia** [comment]
For creating a block blob, `Content-MD5` and `x-ms-blob-content-md5` are interchangeable. So this behavior is expected. However, the document should make it clear. We will close this issue in this repo and update the document. Thanks.
