### ISSUE TITLE
Can we downgrade mime-types gem version to (=1.25.1)

### ISSUE THREAD

**Issue by zeeshan-arshad-confiz** [Azure/azure-storage-ruby#67]
Currently azure-storage is using mime-types (~> 2.0) gem version.

If we downgrade mime-types version to (=1.25.1), will there be any breaking changes?

**Comment by yaxia** [comment]
It won't break the build, but the new or updated MIME types introduced in mime-types v2.0 will not be recognized. Why do you need this old version?

**Comment by zeeshan-arshad-confiz** [comment]
Hi Yaxia,

Thanks for your quick reply.

We are working on open source [OneOps](oneops.com)(https://github.com/oneops/circuit-oneops-1) and adding Azure Resource Manager support in it using fog-azure-rm.

OneOps strictly depends on old version of mime-types i.e. 1.25.1. Upgrading mime-types in OneOps requires a lot of rework and fixing of breaking changes. On the other hand, if downgrading mime-types version in azure-storage does not break anything. We can very quickly add support for Azure resource manager using fog-azure-rm in OneOps. 

We need your support in this regard. Please let us know.

Thanks,

**Comment by yaxia** [comment]
Thanks for providing the information. I will investigate to figure out a way for better dependency tolerance. Please stay tuned.

**Comment by abbas-sheikh-confiz** [comment]
Hi @yaxia 
Please update on this.

Thanks,

**Comment by yaxia** [comment]
0.11.4-preview will remove the constrain. Please have a try. Thanks.

**Comment by zeeshan-arshad-confiz** [comment]
Hi @yaxia 
Thats great. 

When are you guys planning to publish that gem?

**Comment by yaxia** [comment]
It is already available on the [RubyGems](https://rubygems.org/gems/azure-storage).

**Comment by zeeshan-arshad-confiz** [comment]
Thanks for the update.
