### ISSUE TITLE
How to set content type while uploading a file to Azure storage?

### ISSUE THREAD

**Issue by sriharshakappala** [Azure/azure-storage-ruby#70]
I wrote a script to copy all the files from my S3 to Azure Storage. The upload process is complete but for all those files the content type is stored as text/plain (while actually the file is a PDF). How to set content type for the file while uploading?

And is there any way to bulk edit the content-type property for all the files?

**Comment by yaxia** [comment]
If you are using `blob_client.create_block_blob` to upload the files, you can set the content-type via the `options` parameter.
```ruby
require 'azure/storage'

client = Azure::Storage::Client.create
blob_client = client.blob_client
blob_client.create_block_blob container_name, blob_name, content, content_type: 'application/pdf'
```
You can refer to the [create_block_blob](http://azure.github.io/azure-storage-ruby/Azure/Storage/Blob.html#create_block_blob-instance_method) for more options.

Regarding the bulk edit, there is no direct API, but you can write a simple script for it:
```ruby
blobs = blob_client.list_blobs container_name
blobs.each do |blob|
  blob_client.set_blob_properties container_name, blob.name, content_type: 'application/pdf'
end
```
You can refer to the [set_blob_properties](http://azure.github.io/azure-storage-ruby/Azure/Storage/Blob.html#set_blob_properties-instance_method) for more details.

**Comment by sriharshakappala** [comment]
Thanks a ton @yaxia! Worked like a charm! :)
How about adding this as part of readme?

**Comment by sriharshakappala** [comment]
@yaxia Looks like `list_blobs` by default returning only 5000 entries. I read the documentation of [list_blobs](http://azure.github.io/azure-storage-ruby/Azure/Storage/Blob/Container.html#list_blobs-instance_method) but still finding it hard on how to use `marker` option and paginate the results. Any pointers here?

**Comment by sriharshakappala** [comment]
Got it! :) I solved it from your reply from this issue! https://github.com/Azure/azure-storage-ruby/issues/65

**Comment by yaxia** [comment]
Glad to know you resolved it.

**Comment by sureshvignesh** [comment]
Was struggling for hours and finally this helped us, Thanks a ton man  @sriharshakappala
