### ISSUE TITLE
How do I setup client using SAS key

### ISSUE THREAD

**Issue by dhd-dixit** [Azure/azure-storage-ruby#73]
Is there any way I can setup client using SAS key instead of storage_access_key as below

client = Azure::Storage::Client.create(:storage_account_name => "your account name", :storage_access_key => "your access key")

**Comment by yaxia** [comment]
Here is a sample which creates a blob client with a SAS token and gets the blob properties.
```ruby
# Sample code of creating a SAS token. Ignore it if you already has a SAS token
sas_generator = Azure::Storage::Core::Auth::SharedAccessSignature.new
sas_token = sas_generator.generate_service_sas_token "#{container_name}/#{block_blob_name}", {service: 'b', resource: 'b', permissions: 'r'}

# Create a blob client with a SAS token
signer = Azure::Storage::Core::Auth::SharedAccessSignatureSigner.new Azure::Storage.storage_account_name, sas_token
client = Azure::Storage::Blob::BlobService.new(signer: signer)
blob_properties = client.get_blob_properties container_name, block_blob_name
```

**Comment by alxx** [comment]
Is this sample still actual? Because I get an error:

```
>> sas_generator = Azure::Storage::Core::Auth::SharedAccessSignature.new 
ArgumentError: Signing key must be provided
```

**Comment by alxx** [comment]
It worked if I gave it the account name and key like this:

sas_generator = Azure::Storage::Core::Auth::SharedAccessSignature.new Azure.config.storage_account_name, Azure.config.storage_access_key

**Comment by alxx** [comment]
It worked by providing the account name and key as parameter to the constructor.

Specifying to them as part of the setup did not work, because:

```
>> Azure::Storage.setup(storage_account_name: "[redacted]", storage_access_key: "[redacted]")
NoMethodError: undefined method `signer' for Azure::Storage::Default:Module
```

A _little_ more documentation would definitely not go amiss here.

**Comment by alxx** [comment]
And then, there's this:

```
>> blob_properties = client.get_blob_properties '[redacted]', '[redacted]'
TypeError: no implicit conversion of nil into String
```

Honestly, most of the sample provided by @yaxia doesn't seem to work.

**Comment by katmsft** [comment]
@alxx  I think it is because the environment variable is not set, if you are creating without passing actual account name/key as parameter.
Please see [this](https://github.com/Azure/azure-storage-ruby#via-environment-variables) for more information.

**Comment by yaxia** [comment]
@alxx  Thanks for the feedback.
The sample code is out of dated as it is based on the code of Dec 2016 which had default environment setup.
Anyway, the error of `NoMethodError: undefined method `signer' for Azure::Storage::Default:Module` is not expected. We will fix it.

**Comment by aelor** [comment]
@katmsft url is not working. [Here](https://github.com/azure/azure-storage-ruby/tree/master/blob#via-environment-variables) is what he pointed to.

**Comment by kumarks1122** [comment]
This helped me.
```
blob_client = Azure::Storage::Blob::BlobService.create(
    storage_account_name: 'account_name',
    storage_sas_token: 'storage_sas_token_string'
    )
```
