### ISSUE TITLE
The subclass of RetryPolicyFilter overriding the method apply_retry_policy fails to retry by setting 'retry_data[:retryable] = true'

### ISSUE THREAD

**Issue by AbelHu** [Azure/azure-storage-ruby#76]
According to the [comments](https://github.com/Azure/azure-storage-ruby/blob/master/lib/azure/storage/core/filter/retry_filter.rb#L55-L67) of the method `apply_retry_policy`, the subclass of `RetryPolicyFilter` should override the method `apply_retry_policy`. If the `apply_retry_policy` of the subclass decides to retry by setting `retry_data[:retryable] = true`, the method `should_retry?` of `RetryPolicyFilter` will override this value in Line [46](https://github.com/Azure/azure-storage-ruby/blob/master/lib/azure/storage/core/filter/retry_filter.rb#L46) so it fails to retry.

Suggest to change
```
    def should_retry?(response, retry_data)
      apply_retry_policy retry_data
      retry_data[:retryable] = retry_data[:count] <= @retry_count
      return false unless retry_data[:retryable]
      
      should_retry_on_local_error? retry_data
      should_retry_on_error? response, retry_data
      return false unless retry_data[:retryable]
      
      adjust_retry_parameter retry_data
    end
```
=>
```
    def should_retry?(response, retry_data)
      retry_data[:retryable] = false
      apply_retry_policy retry_data
      return false if retry_data[:count] > @retry_count
      
      retryable = retry_data[:retryable] || should_retry_on_local_error? retry_data || should_retry_on_error? response, retry_data
      return false unless retryable
      
      adjust_retry_parameter retry_data
    end
```

**Comment by yaxia** [comment]
Thanks for your feedback. I will evaluate your solution and update the fix plan.

**Comment by yaxia** [comment]
We will fix it in the upcoming release.

**Comment by yaxia** [comment]
@AbelHu Please try 0.12.0-preview for the fix. Thanks.

**Comment by AbelHu** [comment]
@yaxia Thanks. We will have a try.
