### ISSUE TITLE
To find blobs from a container based on metadata

### ISSUE THREAD

**Issue by puneetloya** [Azure/azure-storage-ruby#88]
set_blob_metadata, the blob can be tagged. Is there a way to supply tags as filter and fetch the blob(s) given the container_name

**Comment by yaxia** [comment]
Azure Storage service doesn't support it yet ([REST API](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs)). The filters can be used are "prefix" and "delimiter" in [`list_blobs`](http://azure.github.io/azure-storage-ruby/Azure/Storage/Blob/Container.html#list_blobs-instance_method).

**Comment by yaxia** [comment]
Revisiting this issue, the [Azure Resource Tag](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-using-tags) doesn't apply to the container or blob level. Storage account is the resource that can be tagged. See:  [Use tags to organize your Azure resources](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-using-tags)

We will consider this feature when storage service has support for it.

**Comment by yaxia** [comment]
Closing it as it is not in plan now. 
@puneetloya  Feel free to reopen it if your feature highly depends on it. We'd like to hear your scenarios. Thanks.

**Comment by thomasclaudiushuber** [comment]
Just wanted to add here that you can filter blobs by metadata by using Azure Search. You can click "Add Azure Search" in the menu of your Storage Account to try it out

![image](https://user-images.githubusercontent.com/7116546/44456891-178c0d80-a602-11e8-8c3e-711136778321.png)
