### ISSUE TITLE
Ruby SDK Will have the ability to create a blob from stream

### ISSUE THREAD

**Issue by ovidiu10** [Azure/azure-storage-ruby#96]
Ruby SDK Will have the ability to create a blob from stream

blob_service.create_blob_from_stream(container,blob,stream), its present in Python SDK. Its reference can be checked at Create Blob Using Stream.
 
I couldn’t find similar API in Ruby SDK, project link is Git link .
 
Could you please let me know if the functionality already exists in Ruby SDK, if yes, how can we use it? Otherwise the timeline for the same feature in Ruby SDK.

**Comment by katmsft** [comment]
Hi @ovidiu10, the functionality already exist in Ruby Client Library. You can reference `it "creates a block blob with IO"` in `.\test\integration\blob\block_blob_test` to use it.
In Ruby Client Library, we does not provide different APIs for string/IO, the content can be passed as a IO object when you do blob operations such as append block, put pages and so on.

**Comment by ovidiu10** [comment]
thanks you
