### ISSUE TITLE
Update nokogiri security update 1.8.1 Released

### ISSUE THREAD

**Issue by mruokojo** [Azure/azure-storage-ruby#97]
Please update dependencies to enable nokogiri security fix.

https://groups.google.com/forum/#!topic/ruby-security-ann/VZtBohEQ2iI

**Comment by katmsft** [comment]
Noted, will take a look. Thanks for reporting.

**Comment by katmsft** [comment]
@mruokojo The validation has passed for nokogiri 1.8.1 with this client library. No issue found. Check it out!
