### ISSUE TITLE
How to create and attach managed disks

### ISSUE THREAD

**Issue by phanindrakalva** [Azure/azure-storage-ruby#98]
is there a way to create and attach managed disks to vm?

**Comment by yaxia** [comment]
@phanindrakalva Managed disks are managed by the `azure-mgmt.-compute` gem. You may refer to page [azure_mgmt_compute](https://github.com/Azure/azure-sdk-for-ruby/tree/master/management/azure_mgmt_compute) and [managed_disk_parameters](https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_compute/lib/generated/azure_mgmt_compute/models/managed_disk_parameters.rb).
